- id: mdwrap
  name: mdwrap
  description: "A python based markdown line wrapper"
  entry: mdwrap
  language: python
  types: [markdown, text]
  require_serial: true
  minimum_pre_commit_version: 2.9.2
