[tool.poetry]
name = "mdwrap"
version = "0.1.0"
description = "A python based markdown line wrapper"
authors = ["Leonard <leocser632@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "mdwrap"}]

[tool.poetry.scripts]
mdwrap = "mdwrap.cli:cli"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"